version: '3.8'

services:
  bot:
    build: .
    container_name: vyatsu-data-analysis-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  data:
